version: 2

sources:
  - name: staging
    database: airy-cortex-297320
    schema: trips_data_all

    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata